
import java.sql.Connection;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.AbstractListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import oracle.jdbc.OraclePreparedStatement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

public class RecipeFrame extends javax.swing.JFrame {

    /**
     * Creates new form RecipeFrame
     */
    //create database handler instance
    DatabaseHandler dbHandler = new DatabaseHandler();
    private ListModel model;
       
    public RecipeFrame() {
        initComponents();
        //initialize and display the date
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("MM/dd/yyyy");
	LocalDateTime now = LocalDateTime.now();
        dateTextView.setText(dtf.format(now));
        
        //frame set in center, do not change the size of the screen
        setLocationRelativeTo(null);
        setResizable(false);
	
        //hide search results view until there is an actual set of results to display
        searchResultsPane.setVisible(false);
        //this code will be use to modify what is displayed in the fridge, method needs to be created to generate fridge items
        fridgeListView.setText("Display fridge items, list nutrition facts.");
        //this will display the generated shopping list
        shoppingListView.setText("generate the shopping list here.");
        //this is the recipe list view in the planner tab, have client to check the boxes
        //that they wish to have a recipe to be entered at the checked time period
        //recipeListView
        //define model as new list.
		model = new ListModel();
		//set list to final for access, and add list items to the list for user selection.
		//final JList list = new JList();
		recipeListView.setModel(new AbstractListModel() {
                        //make a sql statement to get data and store in the array here
			String[] values = new String[] {"Pizza", "MashedPotatoes", "Chicken", "Ramen noodles", "Guano", "Hot Hoggies", "Toaster Stroodle"};
			public int getSize() {
				return values.length;
			}
			public Object getElementAt(int index) {
				return values[index];
			}
		});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        RecipeSearchText = new javax.swing.JTextField();
        SearchGo = new javax.swing.JButton();
        ManagerSheet = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fridgeListView = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        shoppingListView = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        DayOfWeekDropMenu = new javax.swing.JComboBox<>();
        recipeListPanel = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        recipeListView = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        moveFromList = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        breakfastPlannerCheckbox = new javax.swing.JCheckBox();
        lunchPlannerCheckbox = new javax.swing.JCheckBox();
        dinnerPlannerCheckbox = new javax.swing.JCheckBox();
        breakfastPlannerTextView = new javax.swing.JTextField();
        lunchPlannerTextView = new javax.swing.JTextField();
        dinnerPlannerTextView = new javax.swing.JTextField();
        clearPlanner = new javax.swing.JButton();
        storeMealPlan = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        radioBreakfast = new javax.swing.JRadioButton();
        radioLunch = new javax.swing.JRadioButton();
        radioDinner = new javax.swing.JRadioButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        RecipeInstructionView = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        RecipeTitleLabel = new javax.swing.JLabel();
        DayOfWeekDropMenu1 = new javax.swing.JComboBox<>();
        addRecipePanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        addRecipeTextField = new javax.swing.JTextField();
        InstructionsLabel = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        recipeInstructionField = new javax.swing.JTextArea();
        storeRecipe = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        recipeCategoryField = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        ingredientNameField = new javax.swing.JTextField();
        caloriesField = new javax.swing.JTextField();
        sodiumField = new javax.swing.JTextField();
        proteinField = new javax.swing.JTextField();
        groupField = new javax.swing.JTextField();
        sugarField = new javax.swing.JTextField();
        fatField = new javax.swing.JTextField();
        ingredientStorebtn = new javax.swing.JButton();
        searchResultsPane = new javax.swing.JPanel();
        searchResultsView = new javax.swing.JScrollPane();
        recipeSearchResultList = new javax.swing.JList<>();
        dateLabel = new javax.swing.JLabel();
        dateTextView = new javax.swing.JTextField();
        clrSearchResults = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuItemSave = new javax.swing.JMenuItem();
        menuItemLoad = new javax.swing.JMenuItem();
        menuItemExit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Search Recipes");
        jLabel1.setToolTipText("");

        RecipeSearchText.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        RecipeSearchText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecipeSearchTextActionPerformed(evt);
            }
        });

        SearchGo.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        SearchGo.setText("GO");
        SearchGo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        fridgeListView.setEditable(false);
        fridgeListView.setColumns(20);
        fridgeListView.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        fridgeListView.setRows(5);
        jScrollPane1.setViewportView(fridgeListView);

        shoppingListView.setColumns(20);
        shoppingListView.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        shoppingListView.setRows(5);
        jScrollPane2.setViewportView(shoppingListView);

        jLabel2.setText("The Fridge");

        jLabel3.setText("The Shopping List");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(251, 251, 251)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        ManagerSheet.addTab("Fridge", jPanel1);

        DayOfWeekDropMenu.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        DayOfWeekDropMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monday", "Tuesday", "Wensday", "Thursday", "Friday", "Saturday", "Sunday" }));
        DayOfWeekDropMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DayOfWeekDropMenuActionPerformed(evt);
            }
        });

        recipeListView.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(recipeListView);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Recipe Selection List");
        jLabel5.setToolTipText("");

        moveFromList.setText(">>");
        moveFromList.setToolTipText("");
        moveFromList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveFromListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout recipeListPanelLayout = new javax.swing.GroupLayout(recipeListPanel);
        recipeListPanel.setLayout(recipeListPanelLayout);
        recipeListPanelLayout.setHorizontalGroup(
            recipeListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recipeListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(recipeListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7)
                    .addGroup(recipeListPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(moveFromList)
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
        );
        recipeListPanelLayout.setVerticalGroup(
            recipeListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recipeListPanelLayout.createSequentialGroup()
                .addGroup(recipeListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(moveFromList))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );

        breakfastPlannerCheckbox.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        breakfastPlannerCheckbox.setText("Breakfast");
        breakfastPlannerCheckbox.setToolTipText("");

        lunchPlannerCheckbox.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lunchPlannerCheckbox.setText("Lunch");
        lunchPlannerCheckbox.setToolTipText("");

        dinnerPlannerCheckbox.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        dinnerPlannerCheckbox.setText("Dinner");
        dinnerPlannerCheckbox.setToolTipText("");

        clearPlanner.setText("Clear");
        clearPlanner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearPlannerActionPerformed(evt);
            }
        });

        storeMealPlan.setText("Store");
        storeMealPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeMealPlanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(breakfastPlannerCheckbox)
                    .addComponent(lunchPlannerCheckbox)
                    .addComponent(dinnerPlannerCheckbox))
                .addGap(8, 8, 8)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(breakfastPlannerTextView, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(lunchPlannerTextView)
                            .addComponent(dinnerPlannerTextView))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(storeMealPlan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clearPlanner)
                        .addGap(40, 40, 40))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(breakfastPlannerCheckbox)
                    .addComponent(breakfastPlannerTextView, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(87, 87, 87)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lunchPlannerCheckbox)
                    .addComponent(lunchPlannerTextView, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(86, 86, 86)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dinnerPlannerCheckbox)
                    .addComponent(dinnerPlannerTextView, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearPlanner)
                    .addComponent(storeMealPlan))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(recipeListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(DayOfWeekDropMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(recipeListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(DayOfWeekDropMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(42, Short.MAX_VALUE))))
        );

        ManagerSheet.addTab("Planner", jPanel2);

        radioBreakfast.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        radioBreakfast.setText("Breakfast");
        radioBreakfast.setToolTipText("");
        radioBreakfast.setActionCommand("radioBreakfast");
        radioBreakfast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBreakfastActionPerformed(evt);
            }
        });

        radioLunch.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        radioLunch.setText("Lunch");
        radioLunch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioLunchActionPerformed(evt);
            }
        });

        radioDinner.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        radioDinner.setText("Dinner");
        radioDinner.setToolTipText("");
        radioDinner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDinnerActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(RecipeInstructionView);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Recipe Instructions");
        jLabel4.setToolTipText("");

        RecipeTitleLabel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        RecipeTitleLabel.setText("Recipe Title");

        DayOfWeekDropMenu1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        DayOfWeekDropMenu1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monday", "Tuesday", "Wensday", "Thursday", "Friday", "Saturday", "Sunday" }));
        DayOfWeekDropMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DayOfWeekDropMenu1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DayOfWeekDropMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(radioBreakfast)
                        .addComponent(radioDinner)
                        .addComponent(radioLunch)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(385, 385, 385))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RecipeTitleLabel)
                        .addGap(385, 385, 385))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RecipeTitleLabel)
                            .addComponent(DayOfWeekDropMenu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radioBreakfast)
                        .addGap(74, 74, 74)
                        .addComponent(radioLunch)
                        .addGap(80, 80, 80)
                        .addComponent(radioDinner)
                        .addGap(118, 118, 118))))
        );

        ManagerSheet.addTab("Meal Plan", jPanel3);

        addRecipePanel.setVerifyInputWhenFocusTarget(false);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Recipe Name");
        jLabel6.setToolTipText("");

        InstructionsLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        InstructionsLabel.setText("Instructions");
        InstructionsLabel.setToolTipText("");

        recipeInstructionField.setColumns(20);
        recipeInstructionField.setRows(5);
        jScrollPane6.setViewportView(recipeInstructionField);

        storeRecipe.setText("Store");
        storeRecipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeRecipeActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel14.setText("Category");

        javax.swing.GroupLayout addRecipePanelLayout = new javax.swing.GroupLayout(addRecipePanel);
        addRecipePanel.setLayout(addRecipePanelLayout);
        addRecipePanelLayout.setHorizontalGroup(
            addRecipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addRecipePanelLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(addRecipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(addRecipePanelLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(recipeCategoryField, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(storeRecipe))
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addRecipeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
            .addGroup(addRecipePanelLayout.createSequentialGroup()
                .addGroup(addRecipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addRecipePanelLayout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jLabel6))
                    .addGroup(addRecipePanelLayout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(InstructionsLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addRecipePanelLayout.setVerticalGroup(
            addRecipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addRecipePanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(addRecipeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(addRecipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addRecipePanelLayout.createSequentialGroup()
                        .addComponent(InstructionsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(storeRecipe))
                    .addGroup(addRecipePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(recipeCategoryField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        ManagerSheet.addTab("Add Recipe", addRecipePanel);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Name");
        jLabel7.setToolTipText("");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("Calories");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("Fat");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("Sodium");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setText("Group");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setText("Proteins");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setText("Sugar");

        ingredientStorebtn.setText("Store");
        ingredientStorebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingredientStorebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(jLabel9))
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(sugarField, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                    .addComponent(fatField)
                                    .addComponent(groupField, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(proteinField)))
                        .addGap(18, 18, 18)
                        .addComponent(ingredientStorebtn))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(32, 32, 32)
                                .addComponent(ingredientNameField, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sodiumField, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                                    .addComponent(caloriesField))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(29, 29, 29))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(ingredientNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(caloriesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(sodiumField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(proteinField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(groupField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(sugarField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(fatField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingredientStorebtn))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(238, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        ManagerSheet.addTab("Add Ingredient", jPanel6);

        recipeSearchResultList.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        searchResultsView.setViewportView(recipeSearchResultList);

        javax.swing.GroupLayout searchResultsPaneLayout = new javax.swing.GroupLayout(searchResultsPane);
        searchResultsPane.setLayout(searchResultsPaneLayout);
        searchResultsPaneLayout.setHorizontalGroup(
            searchResultsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchResultsPaneLayout.createSequentialGroup()
                .addComponent(searchResultsView)
                .addContainerGap())
        );
        searchResultsPaneLayout.setVerticalGroup(
            searchResultsPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchResultsPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(searchResultsView, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        dateLabel.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        dateLabel.setText("Today:");
        dateLabel.setToolTipText("");

        dateTextView.setEditable(false);
        dateTextView.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        dateTextView.setToolTipText("");

        clrSearchResults.setText("CLR");
        clrSearchResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrSearchResultsActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        menuItemSave.setText("Save");
        menuItemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSaveActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemSave);

        menuItemLoad.setText("Load");
        menuItemLoad.setToolTipText("");
        menuItemLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLoadActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemLoad);

        menuItemExit.setText("Exit");
        menuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExitActionPerformed(evt);
            }
        });
        jMenu1.add(menuItemExit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ManagerSheet, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchResultsPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(RecipeSearchText, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14)
                                        .addComponent(SearchGo, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(clrSearchResults, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(319, 319, 319)
                                        .addComponent(dateLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dateTextView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 2, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateLabel)
                    .addComponent(dateTextView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(RecipeSearchText, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(clrSearchResults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SearchGo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(559, 559, 559))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ManagerSheet, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(searchResultsPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        ManagerSheet.getAccessibleContext().setAccessibleName("Fridge");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //search button listener
    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        ArrayList recipeSearchList = new ArrayList();
        //collect recipe objects
        recipeSearchList.add(DatabaseHandler.searchRecipes(RecipeSearchText.getText()));
        
        model = new ListModel();
        
        //get each element and add to the model
        for(int i = 0; i < recipeSearchList.size(); i++){
            Recipe rec = (Recipe) recipeSearchList.get(i);
            String str = rec.getName();
            model.add(str);
        }
        
        //then get collection, add model to the list
        recipeSearchResultList.setModel(model);
        //allow user to see search results
        searchResultsPane.setVisible(true);
        
        //at this point we may need to consider, that the user might want to select an item from the search list
    }//GEN-LAST:event_searchActionPerformed
   
    private void radioBreakfastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBreakfastActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioBreakfastActionPerformed

    private void radioLunchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioLunchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioLunchActionPerformed

    private void radioDinnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDinnerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioDinnerActionPerformed

    private void menuItemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSaveActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_menuItemSaveActionPerformed

    private void menuItemLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLoadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemLoadActionPerformed

    private void menuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExitActionPerformed
        // exit the program when selected
        System.exit(0);
    }//GEN-LAST:event_menuItemExitActionPerformed

    private void moveFromListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveFromListActionPerformed
        // test cases for checkbox selections
        if(breakfastPlannerCheckbox.isSelected() && lunchPlannerCheckbox.isSelected() && dinnerPlannerCheckbox.isSelected()){
            breakfastPlannerTextView.setText(recipeListView.getSelectedValue());
            lunchPlannerTextView.setText(recipeListView.getSelectedValue());
            dinnerPlannerTextView.setText(recipeListView.getSelectedValue());
        }  else if(breakfastPlannerCheckbox.isSelected()){
            if(lunchPlannerCheckbox.isSelected()){
                breakfastPlannerTextView.setText(recipeListView.getSelectedValue());
                lunchPlannerTextView.setText(recipeListView.getSelectedValue());
            } else if(dinnerPlannerCheckbox.isSelected()) {
                breakfastPlannerTextView.setText(recipeListView.getSelectedValue());
                dinnerPlannerTextView.setText(recipeListView.getSelectedValue());
            } else {
                breakfastPlannerTextView.setText(recipeListView.getSelectedValue());
            }
        } else {
            if(lunchPlannerCheckbox.isSelected()) {
                if(dinnerPlannerCheckbox.isSelected()){
                    lunchPlannerTextView.setText(recipeListView.getSelectedValue());
                    dinnerPlannerTextView.setText(recipeListView.getSelectedValue());
                } else {
                    lunchPlannerTextView.setText(recipeListView.getSelectedValue());
                }
            } else if(dinnerPlannerCheckbox.isSelected()){
                dinnerPlannerTextView.setText(recipeListView.getSelectedValue());
            } else {
                //do nothing, could add tip here, no items selected.
            }
        }
    }//GEN-LAST:event_moveFromListActionPerformed

    private void ingredientStorebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingredientStorebtnActionPerformed
        
        //insert ingredients to db
        Ingredient i = new Ingredient(ingredientNameField.getText(), Integer.parseInt(caloriesField.getText()), Integer.parseInt(fatField.getText()),
                                    Integer.parseInt(sodiumField.getText()), groupField.getText(), Integer.parseInt(proteinField.getText()), Integer.parseInt(sugarField.getText()));
        
        DatabaseHandler.insertIngredient(i);
        
        //clear all fields
        ingredientNameField.setText("");
        caloriesField.setText("");
        fatField.setText("");
        sodiumField.setText("");
        groupField.setText("");
        proteinField.setText("");
        sugarField.setText("");
    }//GEN-LAST:event_ingredientStorebtnActionPerformed

    private void storeRecipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeRecipeActionPerformed
         /*
        Since DatabaseHandler's methods create the connection and close them in its
        own methods there is no reason to establish another connection.
        */
         
        //insert recipe and instructions
        //need to make recipe object
        Recipe r = new Recipe(addRecipeTextField.getText(), recipeInstructionField.getText(), recipeCategoryField.getText());
        
        //n should be the number of ingredients chosen by the user.
        int n = 0;
        Ingredient[] ingredients = new Ingredient[n];
        //will need to add the chosen ingredients to the array so that addRecipe can be called.
        DatabaseHandler.addRecipe(r,ingredients);       
        //clear fields
        addRecipeTextField.setText("");
        recipeInstructionField.setText("");
        recipeCategoryField.setText("");      
    }//GEN-LAST:event_storeRecipeActionPerformed

    private void clearPlannerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearPlannerActionPerformed
        // TODO add your handling code here:
        breakfastPlannerTextView.setText("");
        lunchPlannerTextView.setText("");
        dinnerPlannerTextView.setText("");
    }//GEN-LAST:event_clearPlannerActionPerformed

    private void DayOfWeekDropMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DayOfWeekDropMenuActionPerformed
        
    }//GEN-LAST:event_DayOfWeekDropMenuActionPerformed

    private void storeMealPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeMealPlanActionPerformed
        // TODO add your handling code here:
        //Get selected items, add the sql in here
        // test cases for checkbox selections
        if(breakfastPlannerCheckbox.isSelected() && lunchPlannerCheckbox.isSelected() && dinnerPlannerCheckbox.isSelected()){
            breakfastPlannerTextView.getText();
            lunchPlannerTextView.getText();
            dinnerPlannerTextView.getText();
        }  else if(breakfastPlannerCheckbox.isSelected()){
            if(lunchPlannerCheckbox.isSelected()){
                breakfastPlannerTextView.getText();
                lunchPlannerTextView.getText();
            } else if(dinnerPlannerCheckbox.isSelected()) {
                breakfastPlannerTextView.getText();
                dinnerPlannerTextView.getText();
            } else {
                breakfastPlannerTextView.getText();
            }
        } else {
            if(lunchPlannerCheckbox.isSelected()) {
                if(dinnerPlannerCheckbox.isSelected()){
                    lunchPlannerTextView.getText();
                    dinnerPlannerTextView.getText();
                } else {
                    lunchPlannerTextView.getText();
                }
            } else if(dinnerPlannerCheckbox.isSelected()){
                dinnerPlannerTextView.getText();
            } else {
                //do nothing
            }
        }
        
        DayOfWeekDropMenu.getSelectedItem();
    }//GEN-LAST:event_storeMealPlanActionPerformed

    private void RecipeSearchTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecipeSearchTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RecipeSearchTextActionPerformed

    private void clrSearchResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrSearchResultsActionPerformed
        // TODO add your handling code here:
        RecipeSearchText.setText("");
        //hide the search results pane
        searchResultsPane.setVisible(false);
    }//GEN-LAST:event_clrSearchResultsActionPerformed

    private void DayOfWeekDropMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DayOfWeekDropMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DayOfWeekDropMenu1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecipeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecipeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecipeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecipeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecipeFrame().setVisible(true);
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> DayOfWeekDropMenu;
    private javax.swing.JComboBox<String> DayOfWeekDropMenu1;
    private javax.swing.JLabel InstructionsLabel;
    private javax.swing.JTabbedPane ManagerSheet;
    private javax.swing.JTextPane RecipeInstructionView;
    private javax.swing.JTextField RecipeSearchText;
    private javax.swing.JLabel RecipeTitleLabel;
    private javax.swing.JButton SearchGo;
    private javax.swing.JPanel addRecipePanel;
    private javax.swing.JTextField addRecipeTextField;
    private javax.swing.JCheckBox breakfastPlannerCheckbox;
    private javax.swing.JTextField breakfastPlannerTextView;
    private javax.swing.JTextField caloriesField;
    private javax.swing.JButton clearPlanner;
    private javax.swing.JButton clrSearchResults;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextField dateTextView;
    private javax.swing.JCheckBox dinnerPlannerCheckbox;
    private javax.swing.JTextField dinnerPlannerTextView;
    private javax.swing.JTextField fatField;
    private javax.swing.JTextArea fridgeListView;
    private javax.swing.JTextField groupField;
    private javax.swing.JTextField ingredientNameField;
    private javax.swing.JButton ingredientStorebtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JCheckBox lunchPlannerCheckbox;
    private javax.swing.JTextField lunchPlannerTextView;
    private javax.swing.JMenuItem menuItemExit;
    private javax.swing.JMenuItem menuItemLoad;
    private javax.swing.JMenuItem menuItemSave;
    private javax.swing.JButton moveFromList;
    private javax.swing.JTextField proteinField;
    private javax.swing.JRadioButton radioBreakfast;
    private javax.swing.JRadioButton radioDinner;
    private javax.swing.JRadioButton radioLunch;
    private javax.swing.JTextField recipeCategoryField;
    private javax.swing.JTextArea recipeInstructionField;
    private javax.swing.JPanel recipeListPanel;
    private javax.swing.JList<String> recipeListView;
    private javax.swing.JList<String> recipeSearchResultList;
    private javax.swing.JPanel searchResultsPane;
    private javax.swing.JScrollPane searchResultsView;
    private javax.swing.JTextArea shoppingListView;
    private javax.swing.JTextField sodiumField;
    private javax.swing.JButton storeMealPlan;
    private javax.swing.JButton storeRecipe;
    private javax.swing.JTextField sugarField;
    // End of variables declaration//GEN-END:variables
}
